### ISSUE TITLE
Generator doesn't simplify diagram in certain cases

### ISSUE THREAD

**Issue by Osspial** [lukaslueg/macro_railroad#22]
If you generate a syntax diagram for this macro:

```rust
macro_rules! isolate_params {
    ($self:ident.$fn:ident(&self $(, $ident:ident: $ty:ty)*)) => ($self.$fn($($ident),*));
    ($self:ident.$fn:ident(&$($lt:tt)? self $(, $ident:ident: $ty:ty)*)) => ($self.$fn($($ident),*));
}
```

The right-hand part of the diagram doesn't get properly collapsed down, resulting in a diagram that looks like this:

![image](https://user-images.githubusercontent.com/16296823/51793557-2ddd5d00-2190-11e9-9825-9286b8916a30.png)

If you simplify the macro a bit, the diagram generator behaves correctly. I've removed the `$self:ident.$fn:ident` prefix here, and the generator behaves as follows:

```rust
macro_rules! isolate_params {
    (&self $(, $ident:ident: $ty:ty)*) => ($self.$fn($($ident),*));
    (&$($lt:tt)? self $(, $ident:ident: $ty:ty)*) => ($self.$fn($($ident),*));
}
```

![image](https://user-images.githubusercontent.com/16296823/51793570-76951600-2190-11e9-99e2-86b99e62c91b.png)

Which is more in line with what I'd expect to see in the first case.

As an aside to this issue: thank you for making this! Having this around has been super helpful for debugging my own macros, and produces output that's much easier to reason about than the `trace_macros` stuff built into the compiler.

**Comment by lukaslueg** [comment]
This is actually expected behavior. The dotted boxes on the right side of both paths are `Groups` as seen by the parser (including rustc), bound by parentheses on both sides. By default, the parser in `macro_railroads` preserves groups and renders them as in your first example above. Also, by preserving them, the optimizer is not allowed to break them apart while folding common sections; either groups fold because they are identical in their entirety or they don't fold at all. There is some lengthy comment about the ups and downs [here](https://github.com/lukaslueg/macro_railroad/blob/a5799f57db786f0958b781f5062cc47c59e44a9e/src/lowering.rs#L136).

If you are using the [web editor](https://lukaslueg.github.io/macro_railroad_wasm_demo/), there is a switch "Preserve groups", which toggles this behaviour. Turned off, both paths in your macro fold completely.

If you are using the library itself, you can [call](https://github.com/lukaslueg/macro_railroad_wasm/blob/5655e8130e62087bde0a5593cfad3d4fcab4e8e7/src/lib.rs#L50) `ungroup()` on the AST after lowering.


Your second example demonstrates a case where the optimizer could do a better job by removing the nested options. This is caused by the fact that both paths in the second example are actually identical. I'll add some code to do that.

**Comment by lukaslueg** [comment]
The recent commits fix the aforementioned problem with `Repeat::AtMostOnce` // `Option`.
